services:
  - type: web
    name: delta-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: DATABASE_URL
        sync: false
